### ISSUE TITLE
Beaconizer for TYPO3 9 LTS

### ISSUE THREAD

**Issue by Epoche-Napoleon** [digicademy/beaconizer#1]
Hello,

will there be a Beaconizer version for TYPO3 9 LTS and when would that be expected?

Best wishes
Michael Gnessner

**Comment by metacontext** [comment]
Hi @Epoche-Napoleon,

a new Beaconizer version for TYPO3 9 LTS has just been released: https://extensions.typo3.org/extension/beaconizer/

Have fun and best wishes!
